- name: Add Haka-metadata provider (Haka-test)
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "<!-- {mark} ANSIBLE MANAGED Hakatestmetadata BLOCK -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |
      <MetadataProvider type="XML" url="https://haka.funet.fi/metadata/haka_test_metadata_signed.xml" backingFilePath="haka-test-metadata.xml" reloadInterval="3600">
        <MetadataFilter type="Signature" certificate="/etc/pki/tls/certs/{{ shibbolethsp_hakatestcrt | basename }}"/>
        <MetadataFilter type="RequireValidUntil" maxValidityInterval="2592000"/>
      </MetadataProvider>
   
- name: Download certificate (Haka-test)
  get_url: url={{ shibbolethsp_hakatestcrt }} dest=/etc/pki/tls/certs/{{ shibbolethsp_hakatestcrt | basename }} mode=0755
