- name: Shibboleth SP | Metadata | MPASSid-test | Configure
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - MPASSid-test metadata -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |2
              <MetadataProvider type="XML" url="{{ shibbolethsp_mpassidtestmd }}" backingFilePath="{{ shibbolethsp_mpassidtestmd | basename }}" reloadInterval="3600">
              </MetadataProvider>
   

