- name: Shibboleth SP | Metadata | suomi.fi test | Configure
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - suomi.fi test metadata -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |2
              <MetadataProvider type="XML" url="{{ shibbolethsp_suomifitestmd }}" backingFilePath="{{ shibbolethsp_suomifitestmd | basename }}" reloadInterval="3600">
              </MetadataProvider>
   

