- name: Add Haka-metadata provider (Haka)
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "<!-- {mark} Haka-metadata ANSIBLE managed -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |
      <MetadataProvider type="XML" uri="https://haka.funet.fi/metadata/haka-metadata.xml" backingFilePath="haka-metadata.xml" reloadInterval="3600">
        <SignatureMetadataFilter certificate="/etc/pki/tls/certs/{{ shibbolethsp_hakacrt | basename }}"/>
        <MetadataFilter type="RequireValidUntil" maxValidityInterval="2592000"/>
      </MetadataProvider>
   
- name: Download certificate (Haka)
  get_url: url={{ shibbolethsp_hakacrt }} dest=/etc/pki/tls/certs/{{ shibbolethsp_hakacrt | basename }} mode=0755
